spring:
  application:
    name: backend
  profiles:
    active: local
  data:
    web:
      pageable:
        default-page-size: 10
  datasource:
    username: ${SQL_USERNAME:admin}
    url: ${SQL_URI:jdbc:postgresql://localhost:5432/fleet_assistant}
    password: ${SQL_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY:keys/private_access.pem}
  public: ${ACCESS_TOKEN_PUBLIC_KEY:keys/public_access.pem}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY:keys/private_refresh.pem}
  public: ${REFRESH_TOKEN_PUBLIC_KEY:keys/public_refresh.pem}
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG