spring:
  application:
    name: backend
  profiles:
    active: local
  data:
    web:
      pageable:
        default-page-size: 10
  datasource:
    username: ${SQL_USERNAME:admin}
    url: ${SQL_URI:jdbc:postgresql://localhost:5432/fleet_assistant}
    password: ${SQL_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: false
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG