name: Test Workflow

on:
  workflow_call:

jobs:
  jacoco:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Run Gradle tests
        run: ./gradlew test --no-daemon

      - name: Generate JaCoCo Report
        run: ./gradlew jacocoTestReport --no-daemon

      - name: Check Generated Report
        run: cat build/reports/jacoco/test/jacocoTestReport.csv

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: server/build/reports/jacoco/test/jacocoTestReport.csv