name: CI for frontend

on:
  pull_request:
    branches:
      - master
      - develop
    paths:
      - 'frontend/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-modules


      - name: Install dependencies
        run: npm install

      - name: Generate environment.ts
        run: |
          chmod +x ./generate-environment.sh
          ./generate-environment.sh

      - name: Run ng build
        run: npm run build:dev

      - name: Run linter tests
        run: npm run lint